test(style): run bash scripts through shellcheck

diff --git a/store/monitor/bin/boot b/store/monitor/bin/boot
--- a/store/monitor/bin/boot
+++ b/store/monitor/bin/boot
@@ -3,15 +3,18 @@
 
 set -e
 
-ETCD_PORT=${ETCD_PORT:-4001}
+ETCD_PORT="${ETCD_PORT:-4001}"
 ETCD="$HOST:$ETCD_PORT"
-ETCD_PATH=${ETCD_PATH:-/deis/store}
-HOSTNAME=`hostname`
+ETCD_PATH="${ETCD_PATH:-/deis/store}"
+HOSTNAME=$(hostname)
 
 function etcd_set_default {
   set +e
-  ERROR="$(etcdctl --no-sync -C $ETCD mk $ETCD_PATH/$1 $2 2>&1 >/dev/null)"
-  if [[ $? -ne 0 && $(echo $ERROR | grep -ive "key already exists") ]]; then
+  ERROR="$(etcdctl --no-sync -C "$ETCD" mk "$ETCD_PATH/$1" "$2" 2>&1 >/dev/null)"
+
+  # We're not compairing output with -n so error doesn't apply
+  # shellcheck disable=SC2143
+  if [[ $? -ne 0 && $(echo "$ERROR" | grep -ive "key already exists") ]]; then
     echo "etcd_set_default: an etcd error occurred ($ERROR)"
     echo "aborting..."
     exit 1
@@ -31,11 +34,11 @@ etcd_set_default pgNum 64 # this gives us a reasonable number of placement group
 # "too many placement groups per host" warning
 etcd_set_default maxPGsPerOSDWarning 1536
 
-if ! etcdctl --no-sync -C $ETCD get ${ETCD_PATH}/monSetupComplete >/dev/null 2>&1 ; then
+if ! etcdctl --no-sync -C "$ETCD" get "${ETCD_PATH}/monSetupComplete" >/dev/null 2>&1 ; then
   echo "store-monitor: Ceph hasn't yet been deployed. Trying to deploy..."
   # let's rock and roll. we need to obtain a lock so we can ensure only one machine is trying to deploy the cluster
-  if etcdctl --no-sync -C $ETCD mk ${ETCD_PATH}/monSetupLock $HOSTNAME >/dev/null 2>&1 \
-  || [[ `etcdctl --no-sync -C $ETCD get ${ETCD_PATH}/monSetupLock` == "$HOSTNAME" ]] ; then
+  if etcdctl --no-sync -C "$ETCD" mk "${ETCD_PATH}/monSetupLock" "$HOSTNAME" >/dev/null 2>&1 \
+  || [[ $(etcdctl --no-sync -C "$ETCD" get "${ETCD_PATH}/monSetupLock") == "$HOSTNAME" ]] ; then
     echo "store-monitor: obtained the lock to proceed with setting up."
 
     # Generate administrator key
@@ -45,32 +48,32 @@ if ! etcdctl --no-sync -C $ETCD get ${ETCD_PATH}/monSetupComplete >/dev/null 2>&
     ceph-authtool /etc/ceph/ceph.mon.keyring --create-keyring --gen-key -n mon. --cap mon 'allow *'
 
     fsid=$(uuidgen)
-    etcdctl --no-sync -C $ETCD set ${ETCD_PATH}/fsid ${fsid} >/dev/null
+    etcdctl --no-sync -C "$ETCD" set "${ETCD_PATH}/fsid" "${fsid}" >/dev/null
 
     # Generate initial monitor map
-    monmaptool --create --add ${HOSTNAME} ${HOST} --fsid ${fsid} /etc/ceph/monmap
+    monmaptool --create --add "${HOSTNAME}" "${HOST}" --fsid "${fsid}" /etc/ceph/monmap
 
-    etcdctl --no-sync -C $ETCD set ${ETCD_PATH}/monKeyring < /etc/ceph/ceph.mon.keyring >/dev/null
-    etcdctl --no-sync -C $ETCD set ${ETCD_PATH}/adminKeyring < /etc/ceph/ceph.client.admin.keyring >/dev/null
+    etcdctl --no-sync -C "$ETCD" set "${ETCD_PATH}/monKeyring" < /etc/ceph/ceph.mon.keyring >/dev/null
+    etcdctl --no-sync -C "$ETCD" set "${ETCD_PATH}/adminKeyring" < /etc/ceph/ceph.client.admin.keyring >/dev/null
 
     # mark setup as complete
     echo "store-monitor: setup complete."
-    etcdctl --no-sync -C $ETCD set ${ETCD_PATH}/monSetupComplete youBetcha >/dev/null
+    etcdctl --no-sync -C "$ETCD" set "${ETCD_PATH}/monSetupComplete" youBetcha >/dev/null
   else
-    until etcdctl --no-sync -C $ETCD get ${ETCD_PATH}/monSetupComplete >/dev/null 2>&1 ; do
+    until etcdctl --no-sync -C "$ETCD" get "${ETCD_PATH}/monSetupComplete" >/dev/null 2>&1 ; do
       echo "store-monitor: waiting for another monitor to complete setup..."
       sleep 5
     done
   fi
 fi
 
-until confd -onetime -node $ETCD --confdir /app --log-level error; do
+until confd -onetime -node "$ETCD" --confdir /app --log-level error; do
   echo "store-monitor: waiting for confd to write initial templates..."
   sleep 5
 done
 
 # If we don't have a monitor keyring, this is a new monitor
-if [ ! -e /var/lib/ceph/mon/ceph-${HOSTNAME}/keyring ]; then
+if [ ! -e "/var/lib/ceph/mon/ceph-${HOSTNAME}/keyring" ]; then
   if [ ! -f /etc/ceph/monmap ]; then
     ceph mon getmap -o /etc/ceph/monmap
   fi
@@ -80,13 +83,13 @@ if [ ! -e /var/lib/ceph/mon/ceph-${HOSTNAME}/keyring ]; then
   ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.mon.keyring
 
   # Make the monitor directory
-  mkdir -p /var/lib/ceph/mon/ceph-${HOSTNAME}
+  mkdir -p "/var/lib/ceph/mon/ceph-${HOSTNAME}"
 
   # Prepare the monitor daemon's directory with the map and keyring
-  ceph-mon --mkfs -i ${HOSTNAME} --monmap /etc/ceph/monmap --keyring /tmp/ceph.mon.keyring
+  ceph-mon --mkfs -i "${HOSTNAME}" --monmap /etc/ceph/monmap --keyring /tmp/ceph.mon.keyring
 
   # Clean up the temporary key
   rm /tmp/ceph.mon.keyring
 fi
 
-exec /usr/bin/ceph-mon -d -i ${HOSTNAME} --public-addr ${HOST}:6789
+exec /usr/bin/ceph-mon -d -i "${HOSTNAME}" --public-addr "${HOST}:6789"
